### ISSUE TITLE
kali报错

### ISSUE THREAD

**Issue by LOSTtokens** [wudicainiao/Fofa-Cscan#3]
[*]开始抓取
Traceback (most recent call last):
  File "fofa-Cscan.py", line 73, in <module>
    creat_xlsx()
  File "fofa-Cscan.py", line 55, in creat_xlsx
    os.mkdir('out')
FileExistsError: [Errno 17] File exists: 'out'

[*]开始抓取
[*]创建文件成功 2019-11-17-02-46.xlsx
Traceback (most recent call last):
  File "fofa-Cscan.py", line 74, in <module>
    [ip(s) for s in ipaddress.ip_network(str(sys.argv[2]),False)]
  File "fofa-Cscan.py", line 74, in <listcomp>
    [ip(s) for s in ipaddress.ip_network(str(sys.argv[2]),False)]
  File "fofa-Cscan.py", line 25, in ip
    [write_xlsx(i) for i in json.loads(res)["results"]]
KeyError: 'results'

**Comment by dacade** [comment]
这是因为你没有充值fofa会员，积分不会，fofa那边就不会返回给你数据，换个fofa会员（充钱的那种会员，而不是注册的那种会员）api就行了。
